<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert(
            [
                [
                    'category_id' => 2,
                    'slug' => 'miu-miu',
                    'name' => 'Miu Miu',
                    'description' => 'Miu Miu là mèo đó',
                    'brand' => 'Ninh Thuận',
                    'selling_price' => '1200000',
                    'original_price' => '1300000',
                    'quantity' => '20',
                    'image' => 'uploads/product/1683206936.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 6,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-beo',
                    'name' => 'mèo béo',
                    'description' => 'mèo béo',
                    'brand' => 'việt nam',
                    'selling_price' => '2000000',
                    'original_price' => '2500000',
                    'quantity' => '3',
                    'image' => 'uploads/product/1735452314.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 6,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'cho-shiba',
                    'name' => 'Chó Shiba',
                    'description' => 'Giống chó Nhật Bản',
                    'brand' => 'Đà Lạt',
                    'selling_price' => '1200000',
                    'original_price' => '1400000',
                    'quantity' => '15',
                    'image' => 'uploads/product/1683206996.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 0,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'cho-ta',
                    'name' => 'Chó ta',
                    'description' => 'Chó ta',
                    'brand' => 'việt nam',
                    'selling_price' => '500000',
                    'original_price' => '600000',
                    'quantity' => '20',
                    'image' => 'uploads/product/1735452535.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 7,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'cho-dang-yeu',
                    'name' => 'Chó đáng yêu',
                    'description' => 'Chó đáng yêu',
                    'brand' => 'úc',
                    'selling_price' => '900000',
                    'original_price' => '1000000',
                    'quantity' => '10',
                    'image' => 'uploads/product/1735452654.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 8,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-trang',
                    'name' => 'Mèo Trắng',
                    'description' => 'Mèo màu trắng',
                    'brand' => 'Ấn Độ',
                    'selling_price' => '1300000',
                    'original_price' => '1400000',
                    'quantity' => '8',
                    'image' => 'uploads/product/1683207088.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 14,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-vang-hoe',
                    'name' => 'Mèo vàng hoe',
                    'description' => 'Mèo vàng hoe',
                    'brand' => 'việt nam',
                    'selling_price' => '500000',
                    'original_price' => '600000',
                    'quantity' => '30',
                    'image' => 'uploads/product/1735453226.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-den-xi',
                    'name' => 'Mèo đen xì',
                    'description' => 'Mèo đen xì',
                    'brand' => 'Anh quốc',
                    'selling_price' => '2000000',
                    'original_price' => '2200000',
                    'quantity' => '10',
                    'image' => 'uploads/product/1735453361.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-dep',
                    'name' => 'Mèo đẹp',
                    'description' => 'Mèo đẹp',
                    'brand' => 'Anh ',
                    'selling_price' => '5000000',
                    'original_price' => '6000000',
                    'quantity' => '25',
                    'image' => 'uploads/product/1735454650.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-be',
                    'name' => 'mèo bé',
                    'description' => 'mèo bé',
                    'brand' => 'việt nam ',
                    'selling_price' => '100000',
                    'original_price' => '200000',
                    'quantity' => '50',
                    'image' => 'uploads/product/1735454813.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 2,
                    'slug' => 'meo-gai',
                    'name' => 'Mèo gái',
                    'description' => 'Mèo gái',
                    'brand' => 'Anh ',
                    'selling_price' => '10000000',
                    'original_price' => '20000000',
                    'quantity' => '19',
                    'image' => 'uploads/product/1735454971.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'chow-chow',
                    'name' => 'Chow Chow',
                    'description' => 'Chó Canada',
                    'brand' => 'Canada',
                    'selling_price' => '13300000',
                    'original_price' => '13400000',
                    'quantity' => '10',
                    'image' => 'uploads/product/1683207152.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 4,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'cau-vang',
                    'name' => 'Cậu Vàng',
                    'description' => 'Bạn Lão Hạc',
                    'brand' => 'Hà Nội',
                    'selling_price' => '13300000',
                    'original_price' => '14300000',
                    'quantity' => '12',
                    'image' => 'uploads/product/1683207204.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 0,
                ],
                [
                    'category_id' => 1,
                    'slug' => 'so-co-la',
                    'name' => 'Sô cô la',
                    'description' => 'Chó này màu nâu',
                    'brand' => 'Ninh Thuận',
                    'selling_price' => '1530000',
                    'original_price' => '1630000',
                    'quantity' => '1',
                    'image' => 'uploads/product/1683207822.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 4,
                ],
                [
                    'category_id' => 3,
                    'slug' => 'ga-mai',
                    'name' => 'gà mái',
                    'description' => 'gà mái',
                    'brand' => 'thái bình',
                    'selling_price' => '200000',
                    'original_price' => '300000',
                    'quantity' => '30',
                    'image' => 'uploads/product/1735383442.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 10,
                ],
                [
                    'category_id' => 4,
                    'slug' => 'chuot-cong',
                    'name' => 'chuột cống',
                    'description' => 'chuột cống',
                    'brand' => 'việt nam  ',
                    'selling_price' => '50000',
                    'original_price' => '80000',
                    'quantity' => '100',
                    'image' => 'uploads/product/1735384223.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 5,
                ],

                [
                    'category_id' => 5,
                    'slug' => 'lon-nai ',
                    'name' => 'lợn nái',
                    'description' => 'lợn nái',
                    'brand' => 'lợn nam định  ',
                    'selling_price' => '1000000',
                    'original_price' => '1500000',
                    'quantity' => '100',
                    'image' => 'uploads/product/1735384597.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 15,
                ],
                [
                    'category_id' => 6,
                    'slug' => 'ca-canh ',
                    'name' => 'cá cảnh',
                    'description' => 'cá cảnh',
                    'brand' => 'malaysia ',
                    'selling_price' => '40000',
                    'original_price' => '50000',
                    'quantity' => '80',
                    'image' => 'uploads/product/1735385320.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 5,
                ],
                [
                    'category_id' => 7,
                    'slug' => 'gau-bac-cuc ',
                    'name' => 'gấu bắc cực',
                    'description' => 'gấu bắc cực',
                    'brand' => 'euro ',
                    'selling_price' => '500000000',
                    'original_price' => '550000000',
                    'quantity' => '5',
                    'image' => 'uploads/product/1735385649.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 6,
                ],
                [
                    'category_id' => 8,
                    'slug' => 'cu-meo ',
                    'name' => 'cú mèo',
                    'description' => 'cú mèo',
                    'brand' => 'asian ',
                    'selling_price' => '700000',
                    'original_price' => '1000000',
                    'quantity' => '10',
                    'image' => 'uploads/product/1735386072.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 11,
                ],
                [
                    'category_id' => 9,
                    'slug' => 'cao-hoang ',
                    'name' => 'cáo hoang',
                    'description' => 'cáo hoang',
                    'brand' => 'america ',
                    'selling_price' => '20000000',
                    'original_price' => '25000000',
                    'quantity' => '3',
                    'image' => 'uploads/product/1735386293.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 12,
                ],
                [
                    'category_id' => 10,
                    'slug' => 'huou-sao',
                    'name' => 'huơu sao',
                    'description' => 'huơu sao',
                    'brand' => 'rusian',
                    'selling_price' => '50000000',
                    'original_price' => '60000000',
                    'quantity' => '8',
                    'image' => 'uploads/product/1735386421.jpg',
                    'featured' => 0,
                    'status' => 1,
                    'count' => 5,
                ],
                [
                    'category_id' => 11,
                    'slug' => 'vit-bay',
                    'name' => 'vịt bay',
                    'description' => 'vịt bay',
                    'brand' => 'việt nam',
                    'selling_price' => '100000',
                    'original_price' => '150000',
                    'quantity' => '500',
                    'image' => 'uploads/product/1735386578.jpg',
                    'featured' => 1,
                    'status' => 1,
                    'count' => 9,
                ],


            ]
        );
    }
}
